image: node:10.6.0

cache:
  paths:
  - node_modules/
  - .yarn

before_script:
  - yarn install

stages:
  - lint
  - bundle
  - test
  - performance
  - deploy

lint:
  stage: lint
  script:
   - yarn run eslint

bundle:
  stage: bundle
  script:
   - yarn run build

test:
  stage: test
  script:
   - yarn test

performance:
  stage: performance
  script:
   - yarn run perf

pages:
  stage: deploy
  script:
  - cd dashboard && yarn install && yarn run build && cd ..
  - mkdir .public
  - cp -r dashboard/build/fonts .public
  - cp dashboard/build/dashboard.* .public
  - cp dashboard/build/index.html .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
